version: '2'

services:
  doberman-consumer:
    container_name: doberman-consumer
    build:
      context: .
      target: consumer
    depends_on:
      - rabbitmq
  doberman:
    container_name: doberman
    build:
      context: .
      target: doberman
    volumes:
      - .:/doberman
    ports:
     - 3000:3000
    depends_on:
      - rabbitmq
  rabbitmq:
    restart: always
    build: ./rabbitmq
    hostname: rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"
  mysql:
    image: mysql:5.5
    ports:
      - 3333:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=doberman
      - MYSQL_ROOT_USER=admin
      - MYSQL_PASSWORD=password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8030:80
    environment:
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=300M
    depends_on:
      - mysql

volumes:
  mysql_data_db:

