version: "3"

services:
  mysql:
    image: mysql:5.5
    ports:
      - 3333:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=doberman
      - MYSQL_ROOT_USER=admin
      - MYSQL_PASSWORD=password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8030:80
    environment:
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=300M
    depends_on:
      - mysql

volumes:
  mysql_data_db: